from fpdf import FPDF
from datetime import datetime


class ResumeMatchReport(FPDF):
    def header(self):
        self.set_font('Helvetica', 'B', 16)
        self.set_fill_color(74, 144, 217)
        self.set_text_color(255, 255, 255)
        self.cell(0, 14, 'AI Resume Matcher - Match Report',
                  fill=True, new_x="LMARGIN", new_y="NEXT")
        self.set_text_color(0, 0, 0)
        self.ln(3)

    def footer(self):
        self.set_y(-15)
        self.set_font('Helvetica', 'I', 8)
        self.set_text_color(128, 128, 128)
        self.cell(0, 10,
                  f'Generated by AI Resume Matcher | Page {self.page_no()}',
                  align='C')

    def section_title(self, title):
        self.set_font('Helvetica', 'B', 12)
        self.set_fill_color(230, 230, 230)
        self.set_text_color(44, 44, 44)
        self.cell(0, 9, f'  {title}',
                  fill=True, new_x="LMARGIN", new_y="NEXT")
        self.ln(2)

    def key_value(self, key, value):
        self.set_font('Helvetica', 'B', 10)
        self.set_text_color(80, 80, 80)
        self.cell(65, 8, f'{key}:',
                  new_x="RIGHT", new_y="LAST")
        self.set_font('Helvetica', '', 10)
        self.set_text_color(30, 30, 30)
        self.cell(0, 8, str(value),
                  new_x="LMARGIN", new_y="NEXT")

    def skill_badges(self, skills, is_matching=True):
        if not skills:
            self.set_font('Helvetica', 'I', 10)
            self.set_text_color(128, 128, 128)
            self.cell(0, 8, '  None found.',
                      new_x="LMARGIN", new_y="NEXT")
            return
        if is_matching:
            self.set_fill_color(0, 180, 70)
            prefix = '+'
        else:
            self.set_fill_color(220, 50, 50)
            prefix = '-'
        self.set_text_color(255, 255, 255)
        self.set_font('Helvetica', 'B', 9)
        line_width = 0
        max_width = 165
        for skill in skills:
            text = f' {prefix} {skill} '
            text_width = self.get_string_width(text) + 3
            if line_width + text_width > max_width:
                self.ln(8)
                line_width = 0
            self.cell(text_width, 6, text,
                      fill=True, new_x="RIGHT", new_y="LAST")
            self.cell(2, 6, '',
                      new_x="RIGHT", new_y="LAST")
            line_width += text_width + 2
        self.ln(10)
        self.set_text_color(0, 0, 0)


def generate_report(match_result,
                    resume_filename="resume.pdf",
                    job_filename="job.pdf"):

    pdf = ResumeMatchReport()
    pdf.set_auto_page_break(auto=True, margin=20)
    pdf.set_margins(15, 15, 15)
    pdf.add_page()

    # Date
    now = datetime.now().strftime("%B %d, %Y at %I:%M %p")
    pdf.set_font('Helvetica', 'I', 9)
    pdf.set_text_color(120, 120, 120)
    pdf.cell(0, 7, f'Generated on: {now}',
             new_x="LMARGIN", new_y="NEXT")
    pdf.set_text_color(0, 0, 0)
    pdf.ln(3)

    # Files
    pdf.section_title('Files Analyzed')
    pdf.key_value('Resume', resume_filename)
    pdf.key_value('Job Description', job_filename)
    pdf.ln(3)

    # Scores
    pdf.section_title('Match Score Summary')
    pdf.key_value('Final Match Score',
                  f"{match_result['final_score']}%")
    pdf.key_value('Score Category',
                  match_result['score_category'])
    pdf.key_value('TF-IDF Text Similarity',
                  f"{match_result['tfidf_score']}%")
    pdf.key_value('Skill Match Score',
                  f"{match_result['skill_score']}%")
    pdf.ln(3)

    # Assessment
    pdf.set_font('Helvetica', '', 10)
    pdf.set_text_color(60, 60, 60)
    assessment = f"Assessment: {match_result['score_message']}"
    advice = f"Advice: {match_result['score_advice']}"
    pdf.set_x(15)
    pdf.multi_cell(180, 7, assessment)
    pdf.set_x(15)
    pdf.multi_cell(180, 7, advice)
    pdf.set_text_color(0, 0, 0)
    pdf.ln(3)

    # Skills overview
    pdf.section_title('Skills Overview')
    pdf.key_value('Total Skills Required',
                  str(match_result['total_job_skills']))
    pdf.key_value('Skills Matched',
                  str(match_result['total_matching']))
    pdf.key_value('Skills Missing',
                  str(match_result['total_missing']))
    pdf.ln(3)

    # Matching skills
    pdf.section_title('Matching Skills')
    pdf.ln(2)
    pdf.skill_badges(match_result['matching_skills'],
                     is_matching=True)
    pdf.ln(2)

    # Missing skills
    pdf.section_title('Missing Skills')
    pdf.ln(2)
    pdf.skill_badges(match_result['missing_skills'],
                     is_matching=False)
    pdf.ln(2)

    # Bonus skills
    if match_result.get('extra_skills'):
        pdf.section_title('Bonus Skills')
        pdf.set_font('Helvetica', '', 10)
        pdf.set_text_color(60, 60, 60)
        extra = ', '.join(match_result['extra_skills'])
        pdf.set_x(15)
        pdf.multi_cell(180, 7, extra)
        pdf.set_text_color(0, 0, 0)
        pdf.ln(3)

    # Footer note
    pdf.ln(3)
    pdf.set_font('Helvetica', 'I', 8)
    pdf.set_text_color(150, 150, 150)
    note = ('This report was generated by AI Resume Matcher. '
            'Scores are based on TF-IDF cosine similarity '
            'and keyword matching algorithms.')
    pdf.set_x(15)
    pdf.multi_cell(180, 6, note)

    return bytes(pdf.output())